#region Using directives
using System;
using System.IO;
using System.Text;
using UAManagedCore;
using FTOptix.HMIProject;
using FTOptix.NetLogic;
using FTOptix.Core;
#endregion

/// <summary>
/// RecipeYamlTemplateGeneratorNetLogic: design-time utility to generate a
/// YAML configuration template in the FTOptix ProjectFiles directory.
/// Helps developers configure recipe families, phase types, and parameter enablement.
/// </summary>
public class CustomRecipeYamlTemplateGeneratorNetLogic : BaseNetLogic
{

    #region GenerateYamlConfigurationTemplate

    /// <summary>
    /// Generate a template YAML configuration file in ProjectFiles.
    /// </summary>
    [ExportMethod]
    public RecipeOperationResult GenerateYamlConfigurationTemplate(
        string outputFileName = "recipe_configuration_template.yaml",
        int familyCount = 1,
        int phaseTypeCount = 20,
        int stepParameterCount = 20,
        bool overwriteExistingFile = false)
    {
        // Validate inputs
        if (string.IsNullOrWhiteSpace(outputFileName))
            return RecipeOperationResult.Fail("InvalidInput", "Output file name cannot be empty.");

        if (familyCount < 1)
            return RecipeOperationResult.Fail("InvalidInput", "familyCount must be >= 1.");
        if (phaseTypeCount < 1 || phaseTypeCount > 20)
            return RecipeOperationResult.Fail("InvalidInput", "phaseTypeCount must be 1..20.");
        if (stepParameterCount < 1 || stepParameterCount > 20)
            return RecipeOperationResult.Fail("InvalidInput", "stepParameterCount must be 1..20.");

        // Resolve ProjectFiles directory
        string projectFilesDir;
        try
        {
            projectFilesDir = RecipeHelpers.GetProjectFilesPath();
        }
        catch (Exception ex)
        {
            return RecipeOperationResult.Fail("ProjectFilesDirectoryNotFound",
                $"Cannot resolve ProjectFiles directory: {ex.Message}");
        }

        if (!Directory.Exists(projectFilesDir))
            return RecipeOperationResult.Fail("ProjectFilesDirectoryNotFound",
                $"ProjectFiles directory does not exist: {projectFilesDir}");

        string fullPath = Path.Combine(projectFilesDir, outputFileName);

        // Check existing file
        if (File.Exists(fullPath) && !overwriteExistingFile)
            return RecipeOperationResult.Fail("YamlTemplateAlreadyExists",
                $"File already exists: {fullPath}. Set overwriteExistingFile=true to overwrite.");

        // Build YAML content
        string yamlContent = BuildYamlTemplate(familyCount, phaseTypeCount, stepParameterCount);

        // Write file
        try
        {
            File.WriteAllText(fullPath, yamlContent, Encoding.UTF8);
        }
        catch (Exception ex)
        {
            return RecipeOperationResult.Fail("StoreError", $"Failed to write file: {ex.Message}");
        }

        Log.Info("RecipeYamlTemplateGeneratorNetLogic", $"YAML template generated: {fullPath}");
        return RecipeOperationResult.Ok($"Template generated: {fullPath}");
    }

    #endregion

    #region YAML builder

    /// <summary>
    /// Build a syntactically valid YAML configuration template string.
    /// Uses manual string building to include comments and ensure formatting.
    /// </summary>
    private string BuildYamlTemplate(int familyCount, int phaseTypeCount, int stepParameterCount)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Recipe Configuration Template");
        sb.AppendLine("# Generated by RecipeYamlTemplateGeneratorNetLogic");
        sb.AppendLine($"# Generated at: {DateTime.UtcNow:O}");
        sb.AppendLine("#");
        sb.AppendLine("# This file defines:");
        sb.AppendLine("#   - Recipe families (keyed by integer family ID)");
        sb.AppendLine("#   - Allowed phase types per family");
        sb.AppendLine("#   - Enabled step parameters per phase type");
        sb.AppendLine("#");
        sb.AppendLine("# Rules:");
        sb.AppendLine("#   - Phase type values must be > 0");
        sb.AppendLine("#   - Step parameter indexes must be 1..20");
        sb.AppendLine("#   - Each allowedPhaseTypes entry must have a phaseTypes config");
        sb.AppendLine("#   - No duplicate phase types or parameter indexes");
        sb.AppendLine();
        sb.AppendLine("recipeFamilies:");

        for (int f = 1; f <= familyCount; f++)
        {
            sb.AppendLine($"  {f}:");
            sb.AppendLine($"    name: \"Recipe family {f}\"");

            // Build allowedPhaseTypes array
            var phaseTypesList = new StringBuilder();
            phaseTypesList.Append("[");
            for (int p = 1; p <= phaseTypeCount; p++)
            {
                if (p > 1)
                    phaseTypesList.Append(", ");
                phaseTypesList.Append(p);
            }
            phaseTypesList.Append("]");
            sb.AppendLine($"    allowedPhaseTypes: {phaseTypesList}");

            sb.AppendLine("    phaseTypes:");

            for (int p = 1; p <= phaseTypeCount; p++)
            {
                sb.AppendLine($"      {p}:");
                sb.AppendLine($"        name: \"Phase type {p}\"");

                // Build enabledStepParameters array
                var paramsList = new StringBuilder();
                paramsList.Append("[");
                for (int sp = 1; sp <= stepParameterCount; sp++)
                {
                    if (sp > 1)
                        paramsList.Append(", ");
                    paramsList.Append(sp);
                }
                paramsList.Append("]");
                sb.AppendLine($"        enabledStepParameters: {paramsList}");
            }
        }

        return sb.ToString();
    }

    #endregion
}
